Foreground yes
TCPSocket 3310
TCPAddr 0.0.0.0
User clamav
DatabaseDirectory /var/lib/clamav
LogTime yes
MaxFileSize 300M
MaxScanSize 300M
StreamMaxLength 300M
MaxRecursion 20
MaxFiles 10000
MaxEmbeddedPE 50M
MaxHTMLNormalize 10M
MaxScriptNormalize 10M
MaxZipTypeRcg 50M
MaxPartitions 50
MaxIconsPE 100
PCREMatchLimit 100000
PCRERecMatchLimit 5000
BytecodeTimeout 60000
